server {
    listen 80;

    # auth 서비스 - auth ALB로 프록시
    location /auth/ {
        proxy_pass http://${AUTH_ALB}/auth/;
        proxy_set_header Host ${AUTH_ALB};
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /board/ {
        proxy_pass http://fastapi-service/board/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /guestbook/ {
        proxy_pass http://fastapi-service/guestbook/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /company/ {
        root /usr/share/nginx/html;
        index index.html;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
