server {
    listen 80;

    location /auth/ {
        proxy_pass http://auth-fastapi-service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    location / {
        return 301 /auth/login;
    }
}
